//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Workflow_databaseEntities1 : DbContext
    {
        public Workflow_databaseEntities1()
            : base("name=Workflow_databaseEntities1")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        //public virtual DbSet<Fase> Fase { get; set; }
        // public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Tarea> Tarea { get; set; }
    }

    public class Tarea
    {
    }
}
